service: lamda-test # NOTE: update this with your service name
provider:
  name: aws
  runtime: nodejs8.10
functions:
  hello:
    handler: handler.hello
    events:
     - http:
         path: /
         method: get
imageResize:
  hello:
    handler: handler.hello
    events:
     - http:
         path: /imageResize
         method: get
 